// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5Sqen8Xfwk5mUuHdOs6Qa1KbFXtvE-J8',
    appId: '1:856130206780:web:2b0b83b22ef873c896d739',
    messagingSenderId: '856130206780',
    projectId: 'ejemplo-ede25',
    authDomain: 'ejemplo-ede25.firebaseapp.com',
    storageBucket: 'ejemplo-ede25.appspot.com',
    measurementId: 'G-4B2BJ5Z8HE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMNQR4yyVj2eMj6HL4VXpCFuvkXNxCqKQ',
    appId: '1:856130206780:android:51948639ee4f290696d739',
    messagingSenderId: '856130206780',
    projectId: 'ejemplo-ede25',
    storageBucket: 'ejemplo-ede25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj4NdCkgHhmrkLOR0raRGFcCxqto-dj3g',
    appId: '1:856130206780:ios:c25792b25544373796d739',
    messagingSenderId: '856130206780',
    projectId: 'ejemplo-ede25',
    storageBucket: 'ejemplo-ede25.appspot.com',
    iosClientId: '856130206780-k02o2ehgnhktt5rfdatijv6up6n9hqtq.apps.googleusercontent.com',
    iosBundleId: 'com.example.ejemplo',
  );
}
